"""more things

Revision ID: e08380a86b71
Revises: 2b924c6a4576
Create Date: 2020-08-13 18:10:56.609119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08380a86b71'
down_revision = '2b924c6a4576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
